name: dart_price
description: Money library that takes care of dealing with double imprecision.
version: 0.0.3
homepage: https://github.com/cedvdb/dart_price

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  decimal: ^2.2.0

dev_dependencies:
  intl: ^0.17.0
  lints: ^1.0.0
  test: ^1.16.0
